plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	compileOnly "maven.modrinth:iris:${project.iris_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

import org.gradle.internal.logging.text.StyledTextOutputFactory;
import static org.gradle.internal.logging.text.StyledTextOutput.Style;

jar {
	inputs.property "archivesName", project.base.archivesName
	version = null

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}

	def natives = []

	def nativeExt = org.gradle.internal.os.OperatingSystem.current().isWindows() ? "dll" : "so"
	def nativeCandidates = [
		file("native/target/release/waylandcraft.${nativeExt}"),
		file("native/target/debug/waylandcraft.${nativeExt}"),
		file("native/target/release/libwaylandcraft.${nativeExt}"),
		file("native/target/debug/libwaylandcraft.${nativeExt}"),
	]
	for(def candidate in nativeCandidates) {
		if(candidate.exists()) {
			from(candidate)
			natives.add("host")
			break
		}
	}

	def targets = org.gradle.internal.os.OperatingSystem.current().isWindows()
		? [ "windows-gnu-x86_64" ]
		: [ "linux-gnu-x86_64", "linux-gnu-arm64" ];

	for(def target in targets) {
		def ext = target.startsWith("windows") ? "dll" : "so"
		def prefix = target.startsWith("windows") ? "" : "lib"
		def f = file("native-libs/${prefix}waylandcraft-${target}.${ext}")
		if(!f.exists()) continue;

		with(copySpec {
			from(f)
		})
		natives.add("${target}")
	}

	if(natives.size() < 1) {
		services
			.get(StyledTextOutputFactory)
			.create("waylandcraft")
			.withStyle(Style.Failure)
			.println("WARNING: Native library not built! The built mod will not contain native code");
	}
}

loom {
	runs {
		client {
			if(org.gradle.internal.os.OperatingSystem.current().isLinux()) {
				environmentVariable("LD_LIBRARY_PATH", "../native/target/release/")
			}
			if(org.gradle.internal.os.OperatingSystem.current().isWindows()) {
				environmentVariable("PATH", "../native/target/release/;" + System.getenv("PATH"))
			}
			environmentVariable("__GL_THREADED_OPTIMIZATIONS", "0")
			environmentVariable("RUST_BACKTRACE", "1")
		}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}
